# Generated by Django 5.2.11 on 2026-02-21 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('max_load_capacity', models.FloatField()),
                ('odometer_reading', models.FloatField()),
                ('license_plate', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(default='available', max_length=20)),
                ('is_out_of_service', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='Status',
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.TextField(choices=[('User', 'user'), ('Fleet Manager', 'Fm'), ('Dispatcher', 'driver'), ('Safty Officer', 'so'), ('Financial Analyst', 'Fa')], default=''),
        ),
    ]
