# Generated by Django 5.2.11 on 2026-02-21 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_repair_trip_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='driver',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'driver'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='App.profile'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='safty_score',
            field=models.FloatField(default=100.0),
        ),
    ]
